version: "3.5"
services:
  broker:
    image: eclipse-mosquitto
    ports:
      - "8883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./certs:/mosquitto/certs
