version: '3'

services:
  mosquitto:
    build: ./mosquitto
    environment:
      - MOSQUITTO_PASSWORDFILE=password.txt
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/certs:/mosquitto/certs
    ports:
      - 8883:8883
